package main

import (
	"fmt"
	"os"
	"strconv"
	"time"

	a "github.com/chlachula/go2/moonYear"
)

func help(msg string) {
	if msg != "" {
		fmt.Println(msg)
	}
	helptext := `Generates html file moonYearYYYY.htm with 28 moon phase icons generated by moonPhases
Usage:
go2 year moonAge_Jan1st [event-file.csv] [web-page-dir] 
Examples:
go2 2024 19.9
go2 2024 19.9 events2024.csv
go2 2024 19.9 events2024.csv /tmp
	`
	fmt.Println(helptext)
}
func main() {
	defer func(start time.Time) {
		fmt.Printf("Elapsed time %s\n", time.Since(start))
	}(time.Now())

	if len(os.Args) < 3 {
		help("Less than 2 expected arguments")
		os.Exit(1)
	}
	year, err := strconv.Atoi(os.Args[1])
	if err != nil {
		help("Error: " + err.Error())
		os.Exit(1)
	}
	moonAgeJanuary1st, err := strconv.ParseFloat(os.Args[2], 64)
	if err != nil {
		help("Error: " + err.Error())
		os.Exit(1)
	}
	csvFileName := ""
	if len(os.Args) > 3 {
		csvFileName = os.Args[3]
	}
	targetDir := "."
	if len(os.Args) > 4 {
		targetDir = os.Args[4]
	}
	a.CreateWebpageWithTable(year, moonAgeJanuary1st, csvFileName, targetDir)
}
